### PR TITLE
Use compile static

### PR DESCRIPTION
**Pull request by carsonip**
The `compile()` function is not called. Use `compileStatic()` instead. Related tests are modified.

### CODE REVIEW

**Comment by tolyo** [comment]
@carsonip Under what version of brunch is `compile()` not called?

**Comment by carsonip** [comment]
@tolyo I am using brunch `2.8.2` which is the latest version.

**Comment by tolyo** [comment]
@carsonip I ll take a look at it

**Comment by tolyo** [comment]
@carsonip warn: html-pages-brunch does not declare target extension for static files, skipping.
This is a breaking change

**Comment by carsonip** [comment]
@tolyo Did you add the two lines?

```
HtmlPages.prototype.extension = 'html';
HtmlPages.prototype.staticTargetExtension = 'html';
```

**Comment by tolyo** [comment]
@carsonip I see that now. It now works but it works only for the `assets` folder, which I don't believe any other plugins optimize for. `assets` exist just to be copied. I could add it as an option but as far as the plugin is concerned, it is meant for `.html` outside of assets folder.

**Comment by carsonip** [comment]
@tolyo You are right. It turns out that my html are static and they are in the assets folder that's probably why the `compile()` didn't work for me. Assets should be html minified though.

**Comment by tolyo** [comment]
@carsonip I'll make the necessary changes for your use-case. Hold tight

**Comment by carsonip** [comment]
@tolyo Sorry that I overlooked the case. This is great, thanks!

**Comment by tolyo** [comment]
@carsonip Done. Update to `2.3.0`

**Pull request merged**
